import { WorkoutPrescription, WorkoutType } from "./types";

export const WORKOUT_CATALOG: Record<WorkoutType, Omit<WorkoutPrescription, "durationMin"|"distanceKm"|"blocks"|"intensity"> & { intensity: WorkoutPrescription["intensity"] }> = {
  CORRIDA_LEVE_Z1Z2: {
    type: "CORRIDA_LEVE_Z1Z2",
    focus: "BASE_AEROBIA",
    title: "Corrida Leve (Z1–Z2)",
    description: "Base aeróbia + recuperação ativa, desenvolvimento mitocondrial e capilarização.",
    intensity: { model: "HYBRID", hrPercentMax: [60, 75], rpe: [2, 3], zoneHint: "Z2" },
    techniqueNotes: ["Respiração confortável", "Cadência estável", "Postura relaxada"],
  },
  CONTINUA_MODERADA: {
    type: "CONTINUA_MODERADA",
    focus: "BASE_AEROBIA",
    title: "Contínuo Moderado",
    description: "Resistência sustentada (ponte entre base e performance).",
    intensity: { model: "HYBRID", hrPercentMax: [75, 82], rpe: [4, 5], zoneHint: "Z3" },
    techniqueNotes: ["Ritmo controlado", "Sem virar prova"],
  },
  TEMPO_RUN: {
    type: "TEMPO_RUN",
    focus: "LIMIAR",
    title: "Tempo Run (Ritmo)",
    description: "Elevação do limiar (LT2) e tolerância ao esforço controlado.",
    intensity: { model: "HYBRID", hrPercentMax: [83, 88], rpe: [6, 7], zoneHint: "Z4", timeInZoneMin: 20 },
    techniqueNotes: ["Forte controlado", "Finaliza com sensação de ter 1 marcha a mais"],
  },
  INTERVALADO_CURTO: {
    type: "INTERVALADO_CURTO",
    focus: "VO2MAX",
    title: "Intervalado Curto",
    description: "VO₂máx + velocidade com repetições curtas (200–400m).",
    intensity: { model: "HYBRID", hrPercentMax: [90, 95], rpe: [8, 9], zoneHint: "Z5" },
    techniqueNotes: ["Técnica limpa", "Recuperação curta e objetiva"],
  },
  INTERVALADO_MEDIO: {
    type: "INTERVALADO_MEDIO",
    focus: "VO2MAX",
    title: "Intervalado Médio",
    description: "Sustentar alta intensidade (600–1000m), forte para 5K/10K.",
    intensity: { model: "HYBRID", hrPercentMax: [88, 94], rpe: [7, 9], zoneHint: "Z5" },
    techniqueNotes: ["Ritmo de 5K/10K", "Pausas consistentes"],
  },
  INTERVALADO_LONGO: {
    type: "INTERVALADO_LONGO",
    focus: "LIMIAR",
    title: "Intervalado Longo",
    description: "Tolerância ao esforço competitivo (1600–3000m), 10K/21K.",
    intensity: { model: "HYBRID", hrPercentMax: [85, 92], rpe: [7, 8], zoneHint: "Z4" },
    techniqueNotes: ["Constância > explosão", "Última repetição parecida com a primeira"],
  },
  FARTLEK_ESTRUTURADO: {
    type: "FARTLEK_ESTRUTURADO",
    focus: "ECONOMIA",
    title: "Fartlek Estruturado",
    description: "Variação metabólica planejada, alternando estímulos de forma objetiva.",
    intensity: { model: "HYBRID", hrPercentMax: [75, 92], rpe: [5, 8] },
    techniqueNotes: ["Trocas com intenção", "Sem aleatoriedade"],
  },
  LONGAO: {
    type: "LONGAO",
    focus: "ENDURANCE",
    title: "Longão",
    description: "Endurance, economia e maior uso de gordura como substrato.",
    intensity: { model: "HYBRID", hrPercentMax: [65, 78], rpe: [3, 4], zoneHint: "Z2" },
    techniqueNotes: ["Constância", "Hidratação e energia planejadas"],
  },
  LONGAO_PROGRESSIVO: {
    type: "LONGAO_PROGRESSIVO",
    focus: "ENDURANCE",
    title: "Longão Progressivo",
    description: "Endurance + controle de ritmo (início leve → final moderado/ritmo).",
    intensity: { model: "HYBRID", hrPercentMax: [65, 85], rpe: [3, 7] },
    techniqueNotes: ["Progredir sem quebrar", "Fechar forte, mas controlado"],
  },
  REGENERATIVO: {
    type: "REGENERATIVO",
    focus: "RECUPERACAO",
    title: "Regenerativo",
    description: "Recuperação ativa muito leve, sem comprometer adaptação.",
    intensity: { model: "HYBRID", hrPercentMax: [55, 70], rpe: [1, 2], zoneHint: "Z1" },
    techniqueNotes: ["Passada curta", "Relaxamento total"],
  },
  FORCA_ESPECIFICA: {
    type: "FORCA_ESPECIFICA",
    focus: "FORCA",
    title: "Força para Corredores",
    description: "Cadeia posterior, core e quadril para melhorar economia e manter pace.",
    intensity: { model: "RPE", rpe: [6, 8] },
    techniqueNotes: ["Técnica perfeita", "Volume compatível com corrida"],
  },
};
