export enum TrainingGoal {
  HYPERTROPHY = "HYPERTROPHY",
  FAT_LOSS = "FAT_LOSS",
  BODY_RECOMPOSITION = "BODY_RECOMPOSITION",
  STRENGTH = "STRENGTH",
  GENERAL_FITNESS = "GENERAL_FITNESS",
  MUSCULAR_ENDURANCE = "MUSCULAR_ENDURANCE",
  CARDIO_CONDITIONING = "CARDIO_CONDITIONING",
  RETURN_TO_TRAINING = "RETURN_TO_TRAINING",
  HYBRID_PERFORMANCE = "HYBRID_PERFORMANCE",
  RUN_SUPPORT = "RUN_SUPPORT",
  CYCLING_SUPPORT = "CYCLING_SUPPORT",
}

export enum TrainingLevel {
  BEGINNER = "BEGINNER",
  BEGINNER_RETURNING = "BEGINNER_RETURNING",
  INTERMEDIATE = "INTERMEDIATE",
  ADVANCED = "ADVANCED",
}

export enum RecoveryLevel {
  LOW = "LOW",
  MODERATE = "MODERATE",
  HIGH = "HIGH",
}

export enum AdherenceLevel {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
}

export enum TrainingEnvironment {
  FULL_GYM = "FULL_GYM",
  BASIC_GYM = "BASIC_GYM",
  HOME_BASIC = "HOME_BASIC",
  HOME_DUMBBELLS = "HOME_DUMBBELLS",
  OUTDOOR = "OUTDOOR",
  HYBRID = "HYBRID",
}

export enum TrainingSplit {
  FULL_BODY_2X = "FULL_BODY_2X",
  FULL_BODY_3X = "FULL_BODY_3X",
  UPPER_LOWER_4X = "UPPER_LOWER_4X",
  PUSH_PULL_LEGS_3X = "PUSH_PULL_LEGS_3X",
  PUSH_PULL_LEGS_6X = "PUSH_PULL_LEGS_6X",
  ABC_3X = "ABC_3X",
  ABCD_4X = "ABCD_4X",
  HYBRID_3X = "HYBRID_3X",
  HYBRID_4X = "HYBRID_4X",
  MINIMALIST_2X = "MINIMALIST_2X",
}

export enum MovementPattern {
  SQUAT = "SQUAT",
  HIP_HINGE = "HIP_HINGE",
  LUNGE = "LUNGE",
  HORIZONTAL_PUSH = "HORIZONTAL_PUSH",
  VERTICAL_PUSH = "VERTICAL_PUSH",
  HORIZONTAL_PULL = "HORIZONTAL_PULL",
  VERTICAL_PULL = "VERTICAL_PULL",
  KNEE_FLEXION = "KNEE_FLEXION",
  KNEE_EXTENSION = "KNEE_EXTENSION",
  HIP_EXTENSION = "HIP_EXTENSION",
  CALF = "CALF",
  CORE_ANTI_EXTENSION = "CORE_ANTI_EXTENSION",
  CORE_ANTI_ROTATION = "CORE_ANTI_ROTATION",
  CORE_ANTI_LATERAL_FLEXION = "CORE_ANTI_LATERAL_FLEXION",
  CARRY = "CARRY",
  CARDIO_STEADY = "CARDIO_STEADY",
  CARDIO_INTERVAL = "CARDIO_INTERVAL",
}

export enum SessionBlockType {
  PRIMARY = "PRIMARY",
  SECONDARY = "SECONDARY",
  ACCESSORY = "ACCESSORY",
  CORE = "CORE",
  CARDIO = "CARDIO",
  FINISHER = "FINISHER",
}

export enum ProgressionType {
  DOUBLE_PROGRESSION = "DOUBLE_PROGRESSION",
  LOAD_PROGRESSION = "LOAD_PROGRESSION",
  DENSITY_PROGRESSION = "DENSITY_PROGRESSION",
  HYBRID_SIMPLE = "HYBRID_SIMPLE",
}

export enum SafetySeverity {
  INFO = "info",
  WARNING = "warning",
  CRITICAL = "critical",
}
