export enum TrainingGoal {
  HYPERTROPHY = "HYPERTROPHY",
  FAT_LOSS = "FAT_LOSS",
  BODY_RECOMPOSITION = "BODY_RECOMPOSITION",
  STRENGTH = "STRENGTH",
  GENERAL_FITNESS = "GENERAL_FITNESS",
  MUSCULAR_ENDURANCE = "MUSCULAR_ENDURANCE",
  CARDIO_CONDITIONING = "CARDIO_CONDITIONING",
  RETURN_TO_TRAINING = "RETURN_TO_TRAINING",
  HYBRID_PERFORMANCE = "HYBRID_PERFORMANCE",
  RUN_SUPPORT = "RUN_SUPPORT",
  CYCLING_SUPPORT = "CYCLING_SUPPORT",
}

export enum TrainingLevel {
  BEGINNER = "BEGINNER",
  BEGINNER_RETURNING = "BEGINNER_RETURNING",
  NOVICE = "NOVICE",
  INTERMEDIATE = "INTERMEDIATE",
  ADVANCED = "ADVANCED",
}

export enum RecoveryProfile {
  LOW = "LOW",
  MODERATE = "MODERATE",
  HIGH = "HIGH",
}
export enum RecoveryLevel {
  LOW = "LOW",
  MODERATE = "MODERATE",
  HIGH = "HIGH",
}

export enum AdherenceProfile {
  LOW = "LOW",
  MODERATE = "MODERATE",
  HIGH = "HIGH",
}
export enum AdherenceLevel {
  LOW = "LOW",
  MODERATE = "MODERATE",
  HIGH = "HIGH",
}

export enum EquipmentProfile {
  BODYWEIGHT = "BODYWEIGHT",
  BASIC_HOME = "BASIC_HOME",
  FULL_GYM = "FULL_GYM",
  MIXED = "MIXED",
}

export enum TrainingEnvironment {
  HOME = "HOME",
  GYM = "GYM",
  OUTDOOR = "OUTDOOR",
  HYBRID = "HYBRID",
}

export enum TrainingSplitType {
  FULL_BODY = "FULL_BODY",
  UPPER_LOWER = "UPPER_LOWER",
  PUSH_PULL_LEGS = "PUSH_PULL_LEGS",
  BODY_PART = "BODY_PART",
}
export enum TrainingSplit {
  FULL_BODY = "FULL_BODY",
  UPPER_LOWER = "UPPER_LOWER",
  PUSH_PULL_LEGS = "PUSH_PULL_LEGS",
  BODY_PART = "BODY_PART",
}

export enum SessionFocus {
  FULL_BODY = "FULL_BODY",
  UPPER = "UPPER",
  LOWER = "LOWER",
  PUSH = "PUSH",
  PULL = "PULL",
  LEGS = "LEGS",
  POSTERIOR_CHAIN = "POSTERIOR_CHAIN",
  CONDITIONING = "CONDITIONING",
  RECOVERY = "RECOVERY",
}

export enum MovementPattern {
  SQUAT = "SQUAT",
  HINGE = "HINGE",
  HIP_HINGE = "HIP_HINGE",
  LUNGE = "LUNGE",
  HORIZONTAL_PUSH = "HORIZONTAL_PUSH",
  VERTICAL_PUSH = "VERTICAL_PUSH",
  HORIZONTAL_PULL = "HORIZONTAL_PULL",
  VERTICAL_PULL = "VERTICAL_PULL",
  CORE = "CORE",
  CORE_ANTI_EXTENSION = "CORE_ANTI_EXTENSION",
  CORE_ANTI_ROTATION = "CORE_ANTI_ROTATION",
  CARRY = "CARRY",
  CARDIO = "CARDIO",
  CARDIO_INTERVAL = "CARDIO_INTERVAL",
  KNEE_FLEXION = "KNEE_FLEXION",
  CALF = "CALF",
}

export enum ExerciseComplexity {
  LOW = "LOW",
  MODERATE = "MODERATE",
  HIGH = "HIGH",
}

export enum AdaptationAction {
  PROGRESS = "PROGRESS",
  MAINTAIN = "MAINTAIN",
  REDUCE_LOAD = "REDUCE_LOAD",
  REDUCE_VOLUME = "REDUCE_VOLUME",
  DELOAD = "DELOAD",
  COMPRESS_TIME = "COMPRESS_TIME",
  SWAP_EXERCISE = "SWAP_EXERCISE",
  REBALANCE_WEEK = "REBALANCE_WEEK",
}

export enum ProgressionType {
  DOUBLE_PROGRESSION = "DOUBLE_PROGRESSION",
  LOAD_PROGRESSION = "LOAD_PROGRESSION",
  DENSITY = "DENSITY",
}

export enum SafetySeverity {
  LOW = "LOW",
  MODERATE = "MODERATE",
  HIGH = "HIGH",
}
